import { SnapshotIn, SnapshotOut } from "mobx-state-tree";
import { NextResponse } from "next/server";

import { Requirement, UserStory } from "@/store/models";

import { ai, generatePrompt, prepareContent, systemPrompt } from "../lib";

export interface GenerateRequirementsRequestBody {
  description: string;
  productOverview: string;
  userStories: SnapshotOut<UserStory>[];
}
export interface GenerateRequirementsResponseBody {
  requirements: SnapshotIn<Requirement>[];
}

export async function POST(request: Request) {
  const { description, productOverview, userStories } =
    (await request.json()) as GenerateRequirementsRequestBody;

  const result = await ai.createChatCompletion({
    model: "gpt-3.5-turbo",
    n: 1,
    temperature: 0,
    messages: [
      { role: "user", content: systemPrompt },
      {
        role: "user",
        content: `description: ${description}`,
      },
      {
        role: "user",
        content: `product overview: ${productOverview}`,
      },
      {
        role: "user",
        content: `user stories: ${userStories
          .map(({ content }) => `- ${content}`)
          .join("\n")}`,
      },
      ...generatePrompt("requirements"),
    ],
  });

  const requirements = result.data.choices[0].message?.content;

  if (requirements == null) {
    return NextResponse.json(
      {
        message: 'No response generated by ai for "requirements"!',
      },
      { status: 502 }
    );
  }

  return NextResponse.json({
    requirements: prepareContent(requirements),
  } as GenerateRequirementsResponseBody);
}
