import { SnapshotIn } from "mobx-state-tree";
import { NextResponse } from "next/server";

import { UserStory } from "@/store/models";

import { ai, generatePrompt, prepareContent, systemPrompt } from "../lib";

export const ENDPOINT = "/api/ai/generate-user-stories";
export interface GenerateUserStoriesRequestBody {
  description: string;
  productOverview: string;
}
export interface GenerateUserStoriesResponseBody {
  userStories: SnapshotIn<UserStory>[];
}

export async function POST(request: Request) {
  const { description, productOverview } =
    (await request.json()) as GenerateUserStoriesRequestBody;

  const result = await ai.createChatCompletion({
    model: "gpt-3.5-turbo",
    n: 1,
    temperature: 0,
    messages: [
      { role: "user", content: systemPrompt },
      {
        role: "user",
        content: `description: ${description}`,
      },
      {
        role: "user",
        content: `product overview: ${productOverview}`,
      },
      ...generatePrompt("user stories"),
      {
        role: "user",
        content: 'Each user story should start with "As a"',
      },
    ],
  });
  const userStories = result.data.choices[0].message?.content;

  if (userStories == null) {
    return NextResponse.json(
      {
        message: 'No response generated by ai for "user stories"!',
      },
      { status: 502 }
    );
  }

  return NextResponse.json({
    userStories: prepareContent(userStories),
  } as GenerateUserStoriesResponseBody);
}
