import { flow, toGenerator } from "mobx-state-tree";

import { Iteration } from "store";
import ai from "store/api";
import { Store } from "store/store";

import {
  generatePrompt,
  generator,
  prepareContent,
  systemPrompt,
} from "./utilities";

const generateUserStories = flow(function* (self: Store) {
  // Generate user stories
  const result = yield* toGenerator(
    ai.createChatCompletion({
      model: "gpt-3.5-turbo",
      n: 1,
      temperature: 0,
      messages: [
        { role: "user", content: systemPrompt },
        {
          role: "user",
          content: `description: ${self.description}`,
        },
        {
          role: "user",
          content: `product overview: ${self.productOverview}`,
        },
        ...generatePrompt("user stories"),
        {
          role: "user",
          content: 'Each user story should start with "As a"',
        },
      ],
    })
  );
  const userStories = result.data.choices[0].message?.content;

  if (userStories == null) {
    throw new Error("No response generated by ai for user stories!");
  }

  self.setUserStories(prepareContent(userStories));
  self.eventTarget.emit("iterationUpdate", Iteration.userStories);
}) as (self_: unknown) => Promise<void>;

export default generator(generateUserStories);
